### ISSUE TITLE
unable to retrieve file names of attachments inside of msg 

### ISSUE THREAD

**Issue by domchik** [ifedoroff/compound-file-js#16]
Hi, 
i am unable to get file names of any attachments inside of msg :
```
const msg  = parser.Msg.fromUint8Array(this.attachment.bytes);

        let attachments = msg.attachments();

        let promises = [];

        attachments.forEach(attachment => {

            promises.push(new Promise(async (resolve) => {
                let subject = "";
                let fileNameProperty = attachment.getProperty(parser.PidTagAttachFilename);
         // this is never returned        
if(!!fileNameProperty) {
                    subject = attachment.getProperty(parser.PidTagAttachFilename);
                } else {
                    subject = "Untitled";
                }
```

Can you please tell me what could be wrong? Thanks

**Comment by ifedoroff** [comment]
Hi @domchik. Can you please share an example of msg file that you are trying to parse for troubleshooting?

**Comment by domchik** [comment]
![1msg](https://user-images.githubusercontent.com/8353123/139808610-6df7ca8b-673a-4b8e-88da-fc8393bb8860.jpg)

I can't attach msg files here, so i renamed the extension to jpg.  You just need to rename it back to .msg 
Thanks  a lot!
