### ISSUE TITLE
Long import not working

### ISSUE THREAD

**Issue by dmoreira** [ifedoroff/compound-file-js#9]
Hi!
I am having issues with the Long import on the file:
https://github.com/ifedoroff/compound-file-js/blob/master/src/CompoundFile.ts

The import was fixed but on the CompoundFile.js file on dist folder from the NPM repo looks like this:
`var Long = __importStar(require("long"));
require("Long");`
But it should look like this:
`var Long = __importStar(require("long"));
require("./Long");`

Any ideas on how to fix this?

Best regards, Davi

**Comment by ifedoroff** [comment]
Hi, Davi @dmoreira! Kindly try out the latest version 1.0.10. It might be that I published incorrectly built version of the project.

**Comment by dmoreira** [comment]
Hi, thanks for your reply.
